<?php include 'views/header.inc'; ?>
based on the <a href="http://www.arabeyes.org" target="_blank">arabeyes</a> <a href="http://www.arabeyes.org/project.php?proj=ITL" target="_blank">itl library</a>.  
	the prayer times are calculated using the <a href="http://svn.arabeyes.org/viewvc/projects/itl/ports/php/" target="_blank">itl php extension</a>.
<br>
logo made using the <a href="http://creatr.cc/creatr">web2.0 logo creatr</a>.

<?php include 'views/footer.inc'; ?>