<head>
<title>waqt.org - muslim prayertimes</title>
<link rel="stylesheet" type="text/css" href="style.css"> 
</head>

<div class="toplinks">
About | <a href="http://github.com/ahmedre/waqt.org">Github</a> 
</div>

<center>
<a href="index.php"><img src="imgs/waqt.png" border="0"></a><br>
based on the <a href="http://www.arabeyes.org">arabeyes</a> <a href="http://www.arabeyes.org/project.php?proj=ITL">itl library</a>.  the prayer times are calculated using the <a href="http://svn.arabeyes.org/viewvc/projects/itl/ports/php/">itl php extension</a>.
<br>
logo made using the <a href="http://creatr.cc/creatr">web2.0 logo creatr</a>.
<hr>
If you have any questions, comments, or suggestions, please feel free to email us at: <a href='ma&#105;l&#116;o&#58;mus%6C&#105;&#109;&#97;d&#109;i%6E&#64;gmail&#46;&#99;om'>&#109;&#117;&#115;&#108;&#105;madmin&#64;&#103;mail&#46;c&#111;m</a>
</center>

<?php include "settings.inc"; ?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("<?php echo $gaCode; ?>");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
