<?php include "settings.inc"; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-type" value="text/html; charset=utf-8">
<meta name="description" content="Muslim prayer times of cities worldwide">
<meta name="keywords" content="prayer, times, muslim, islam, waqt, salah">
<meta name="Distribution" content="Global">
<meta name="Rating" content="General">
<link rel="stylesheet" type="text/css" href="style.css">
<title>Waqt.org - Muslim Prayer Times</title>
</head>

<body>
<?php // $toolbar_make_conn = true; include "toolbar.inc"; ?>
<div style="height:3px">&nbsp;</div>
<div style="height:1px; background-color:#ef9a10">&nbsp;</div>
<?php include 'views/nav.inc'; ?>
<div id="main">
<div style="padding-top:10px;padding-bottom:40px"><a id="logo" href="/"><img src="imgs/waqt.jpg" border="0" ></a></div>
